import React from 'react'



const Location = (props) => {
   
const location = props.selectedProfile;


  return (
      <div>
            {/* <h1>idUserPrivileges{location.idUserPrivileges}</h1>
            <h1>idUser{location.User_idUser}</h1>
            <h1>idStore{location.Store_idStore}</h1>
            <h1>UserProfile_idUserProfile{location.UserProfile_idUserProfile}</h1>
            <h1>isAutoGenerated{location.isAutoGenerated}</h1> */}
            <h1>Store:{Object.keys(location.store).map((key) => {
                return <div>{location.store[key]}</div>;
            })}</h1>
            <h1>User profile:{Object.keys(location.userprofile).map((key) => {
                return <div>{location.userprofile[key]}</div>;
            })}</h1>

      </div>
    
  )
}


export default Location